spring.application.name=aution
# ==========================================
#  PostgreSQL Database Configuration (Neon)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-wispy-frost-ao2imsbl-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_g0Zep2uJPSWE
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
#  JPA / Hibernate Settings
# ==========================================
# 'update' will automatically create/modify database tables based on your Java entities

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Tuning (Keeps things healthy under high-concurrency background writing)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


#  openssl rand -base64 64
jwt.secret=aB3kR7mN2pQ9sT4vW6xY1zA8bC5dE0fG3hI6jK9lM2nO5pR8sU1vX4yZ7wA0bD
jwt.expiration.ms=86400000


logging.level.org.springframework.security=DEBUG

